import Head from "next/head";
import { Input, CreditCardInput } from "react-ui";
import "react-ui/css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>UI Library Consumer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form className="filepond--image-preview-markup">
          <div>
            <Input id="name" label="Name" />
          </div>
          <div>
            <CreditCardInput />
          </div>
        </form>
      </main>
    </div>
  );
}
